name: flutter_ui_common
description: UI flutter demo
version: 0.0.1
homepage: https://github.com/ho-doan/ui_github

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: